### ISSUE TITLE
Unused code and UI resources

### ISSUE THREAD

**Issue by trisk** [rastapasta/pokemon-go-xposed#1]
Hey, the module works great but I noticed there's quite a bit of unused code including the test classes and what seem to be unneeded declared dependencies on `org.apache.commons:commons-lang3:3.4` and `com.android.support:appcompat-v7:23.4.0`. There's also unused UI resources in the APK. This is adding more than 1Mbyte to the APK size.

Are you planning to use these or were they from a project template? I've only used ant to build Android projects before so I'm not sure where the extra resources are coming from or how to remove them yet.

**Comment by rastapasta** [comment]
It's my first ever Android project, so bare with me 😄 

Using commons-lang3 for the serialization of the object (via org.apache.commons.lang3.SerializationUtils)

 com.android.support:appcompat-v7 was added by android studio afaik.

Any optimizations are more than welcome! ❤️
