### ISSUE TITLE
Button to hide from launcher

### ISSUE THREAD

**Issue by Xhatry** [rastapasta/pokemon-go-xposed#10]
Hi, great work with your xposed module, I love it. It would be nice to see a hide from launcher menu, as it now has an interface, and would be good for those of us who likes to have the launcher clean of xposed modules to open them in the xposed installer app. Many xposed modules do have this option, an it is very cool. Thank you for your amazing work!

**Comment by rastapasta** [comment]
Thanks for the kudos and the idea - will investigate and implement ;)

**Comment by rastapasta** [comment]
Done, thanks for your idea! ❤️
