### ISSUE TITLE
Error with *.clients.google.com

### ISSUE THREAD

**Issue by Cronick** [rastapasta/pokemon-go-xposed#12]
Seems like there is an error right now about, where it's also rewriting the url for *.clients.google.com.
Since it redirects these requests to the custom endpoint. It seems like with the use of POGOserver, that the map ingame is not showing up correctly, as the server is not expected to handle there requests.

I think there is some need for small filter to let the requests for *.clients.google.com passing thought, so it should show the map ingame.

From the xposed log: https://vgy.me/U5wT0k.png

**Comment by maierfelix** [comment]
@Cronick better intercept the traffic, instead of just ignoring it. So we have choice about what to do with it

**Comment by maierfelix** [comment]
Great work! @fehnomenal
