### ISSUE TITLE
Seems to not work

### ISSUE THREAD

**Issue by RikudouSage** [rastapasta/pokemon-go-xposed#14]
I started building own PoGo server so I need to redirect all traffic to my computer, but it does not seem to work. I have issued a self signed certificate for the server and set your app to connect to 192.168.1.130:443. Right now the "server" just logs the request uri so I know whether the app goes there. My log is empty, so there wasn't any request to the app. Can you help me on that?

**Comment by rastapasta** [comment]
dont' set a port number as a endpoint overwrite, it uses 80 if the ssl-support is unset, 443 if set.
prefer to not use ssl in your local setup.

hope that helped :) Cheers!
