### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by blackms** [rastapasta/pokemon-go-xposed#4]
Hello, I installed the module, and the CA certificate inside Nox, but I'm still not able to login inside Pogo, have you an idea about what am i missing?

**Comment by rastapasta** [comment]
Have you activated the module and restarted your phone? Cheers!

**Comment by blackms** [comment]
I did, activated and restarted, still no way to login :)

**Comment by rastapasta** [comment]
Hummm proxy setup? And could you try to use another MITM project to see if its an issue with Nox? Sorry for the inconvenience, first problem with the module that I'm hearing of ;)

**Comment by blackms** [comment]
Solved, thanks :D
