### ISSUE TITLE
Just wondering... 

### ISSUE THREAD

**Issue by TheJaake** [rastapasta/pokemon-go-xposed#8]
Could I somehow be banned by using this? Niantic says that if you get caught using any 3rd party software you can get banned. Is there any way that niantic would find out that I am using this module or my pogo optimizer mitm certificate?

**Comment by rastapasta** [comment]
This module by itself should be undetectable for them - its whole purpose is to simulate the native code, that the original certificates were used to connect to the API. So whatever check they implement, the only data source for this check is the injected trust chain.
As long as your 3rd party solution isn't injecting own requests (without proper signing), all should be good and not detectable on their side. Happy MITMing! 😄

**Comment by TheJaake** [comment]
Okay. Thanks! That's nice to know. :D
